{"name": "test_TS_002", "status": "passed", "attachments": [{"name": "Error with xyzabc123", "source": "bbd20201-a6c2-4c00-98c3-c311bad3dd02-attachment.png", "type": "image/png"}, {"name": "Error at<class 'TC_LF_004.Test_invalid_pass'>", "source": "958aaf03-4845-45b1-a529-06cdab2a2e9e-attachment.png", "type": "image/png"}, {"name": "Validation error occurred....", "source": "f84fad9a-ef02-48a7-b4cb-bce3b8b78b71-attachment.png", "type": "image/png"}, {"name": "log", "source": "e3dc9ce6-053c-41e8-87ac-2bb7e99a22f6-attachment.txt", "type": "text/plain"}], "start": 1740900266167, "stop": 1740900271352, "uuid": "d4eccc62-13f2-4f10-8748-45d83ba3d6ed", "historyId": "1e00eadf4f436c91f83617f5a014dfd4", "testCaseId": "1e00eadf4f436c91f83617f5a014dfd4", "fullName": "testCases.Login  Test Cases.TC_LF_004.Test_invalid_pass#test_TS_002", "labels": [{"name": "parentSuite", "value": "testCases.Login  Test Cases"}, {"name": "suite", "value": "TC_LF_004"}, {"name": "subSuite", "value": "Test_invalid_pass"}, {"name": "host", "value": "DESKTOP-DL1JSBI"}, {"name": "thread", "value": "15828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.Login  Test Cases.TC_LF_004"}]}