{"name": "test_data_driven_testing[ndj@mailinator.com-a4iM2@qJaP7U4AS-Valid]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_004_DDT.Test_Data_Driven object at 0x000001BA8420E210>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"89894dabce2a968994885e6b108e8c99\")>, username = 'ndj@mailinator.com'\npassword = 'a4iM2@qJaP7U4AS', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(f\"Starting test for: {username}\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Capture Screenshot after Login\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"After_Login_{username}\",\n                          attachment_type=AttachmentType.PNG)\n    \n            # Validate Result\n            self.actual_result = self.lp.myaccount_page()\n            self.logger.info(f\"Actual: {self.actual_result}, Expected: {expected_result}\")\n            if self.actual_result.strip().lower() in [\"exceeded\",\"unknown\"]:\n                self.actual_result = \"Invalid\"\n            # Assert and Capture Failures\n            if self.actual_result.strip().lower() == expected_result.strip().lower():\n                self.logger.info(f\"Test Passed for {username}\")\n                assert True\n            else:\n                self.logger.error(f\"Test Failed for {username}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=f\"Failure_{username}\",\n                              attachment_type=AttachmentType.PNG)\n>               assert False\nE               assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:58: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_004_DDT.Test_Data_Driven object at 0x000001BA8420E210>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"89894dabce2a968994885e6b108e8c99\")>, username = 'ndj@mailinator.com'\npassword = 'a4iM2@qJaP7U4AS', expected_result = 'Valid'\n\n    @pytest.mark.parametrize(\"username, password, expected_result\", get_exceldata(path, \"Sheet1\"))\n    def test_data_driven_testing(self, setup, username, password, expected_result):\n        self.logger.info(f\"Starting test for: {username}\")\n    \n        self.driver = setup\n        self.driver.maximize_window()\n    \n        try:\n            # Navigate to Login Page\n            self.driver.get(self.baseurl)\n            self.hp = Homepage(self.driver)\n            self.hp.clickmyaccount()\n            self.hp.clicklogin()\n            self.ma = My_Account_page(self.driver)\n    \n            # Perform Login\n            self.lp = Login(self.driver)\n            self.lp.click_email(username)\n            self.lp.click_password(password)\n            self.lp.click_login()\n    \n            # Capture Screenshot after Login\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"After_Login_{username}\",\n                          attachment_type=AttachmentType.PNG)\n    \n            # Validate Result\n            self.actual_result = self.lp.myaccount_page()\n            self.logger.info(f\"Actual: {self.actual_result}, Expected: {expected_result}\")\n            if self.actual_result.strip().lower() in [\"exceeded\",\"unknown\"]:\n                self.actual_result = \"Invalid\"\n            # Assert and Capture Failures\n            if self.actual_result.strip().lower() == expected_result.strip().lower():\n                self.logger.info(f\"Test Passed for {username}\")\n                assert True\n            else:\n                self.logger.error(f\"Test Failed for {username}\")\n                allure.attach(self.driver.get_screenshot_as_png(), name=f\"Failure_{username}\",\n                              attachment_type=AttachmentType.PNG)\n                assert False\n    \n        except Exception as e:\n            self.logger.error(f\"Unexpected error: {e}\")\n            allure.attach(self.driver.get_screenshot_as_png(), name=f\"Unexpected_Error_{username}\",\n                          attachment_type=AttachmentType.PNG)\n>           assert False\nE           assert False\n\ntestCases\\Data Driven Test\\test_004_DDT.py:64: AssertionError"}, "attachments": [{"name": "After_Login_ndj@mailinator.com", "source": "e267d00f-425c-4f01-a299-0553caa28419-attachment.png", "type": "image/png"}, {"name": "Failure_ndj@mailinator.com", "source": "68529708-d308-44b9-84fa-0c1c0ffc0b2f-attachment.png", "type": "image/png"}, {"name": "Unexpected_Error_ndj@mailinator.com", "source": "03c88cb5-38c7-49e7-ba1c-2a0aaae4b3f3-attachment.png", "type": "image/png"}, {"name": "log", "source": "950f0d8d-6681-42b4-b82a-45b9250bd01e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'ndj@mailinator.com'"}, {"name": "password", "value": "'a4iM2@qJaP7U4AS'"}, {"name": "expected_result", "value": "'Valid'"}], "start": 1740910803538, "stop": 1740910821723, "uuid": "dac056ce-d9b7-44fc-a34b-ddda0f22ea23", "historyId": "5824f2dfec43c90d8f7bae3ad7be7a74", "testCaseId": "feaf2845cd517faac78063da184e07ae", "fullName": "testCases.Data Driven Test.test_004_DDT.Test_Data_Driven#test_data_driven_testing", "labels": [{"name": "parentSuite", "value": "testCases.Data Driven Test"}, {"name": "suite", "value": "test_004_DDT"}, {"name": "subSuite", "value": "Test_Data_Driven"}, {"name": "host", "value": "DESKTOP-DL1JSBI"}, {"name": "thread", "value": "324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCases.Data Driven Test.test_004_DDT"}]}